# Nome da aplicação
spring.application.name=ecommerce-api

# Isso faz com que seja criado automaticamente a tabela product no banco de dados, baseado na classe Products
spring.jpa.hibernate.ddl-auto=update

# Configurando a URL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/ecommerce_db

# Nome que configurei no Docker
spring.datasource.username=postgres

# Senha presente no Docker
spring.datasource.password=Portifolio123

# Para mostrar o log do SQL gerado pelo Spring
spring.jpa.show-sql=true

# Forçando o Flyway a usar as credenciais corretas
spring.flyway.user=postgres
spring.flyway.password=Portifolio123

# mais tempo para o banco de dados inicializar
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=30000

# teste para saber se o arquivo está sendo lido
server.port=9090